[workspace]
members = [
    "escrow"
]

resolver = "2"

[workspace.dependencies]
arrayref = "0.3.8"
solana-program = "2.0.0"
spl-token = { version = "6.0.0", features = ["no-entrypoint"] }
thiserror = "1.0.63"
